name: Publish toolkit to GitHub Packages

on:
  push:
    branches:
      - dev

jobs:
  determine-modules:
    runs-on: ubuntu-22.04
    outputs:
      modules: ${{ steps.changed-modules.outputs.modules }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.0
        with:
          fetch-depth: 0  # 모든 커밋 히스토리 가져오기

      - name: Determine changed modules
        id: changed-modules
        run: |
          MODULES=$(git diff --name-only HEAD~1 HEAD | grep '^modules/' | cut -d'/' -f2 | sort | uniq | jq -R -s -c 'split("\n")[:-1]')
          if [[ -z "$MODULES" || "$MODULES" == "null" ]]; then MODULES="[]"; fi
          echo "modules=$MODULES" >> $GITHUB_OUTPUT

  publish:
    needs: determine-modules
    if: needs.determine-modules.outputs.modules != '[]'
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        module: ${{ fromJson(needs.determine-modules.outputs.modules) }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Publish changed module
        run: ./gradlew :modules:${{ matrix.module }}:publish
        env:
          GITHUB_USERNAME: ${{ secrets.GITHUB_USERNAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
