name: Publish toolkit to GitHub Packages

on:
  push:
    branches:
      - dev

jobs:
  determine-modules:
    runs-on: ubuntu-22.04
    outputs:
      modules: ${{ steps.changed-modules.outputs.modules }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.0
        with:
          fetch-depth: 0  # 모든 커밋 히스토리 가져오기

      - name: Set up JDK 21
        uses: actions/setup-java@v4.0.0
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Determine changed modules
        id: changed-modules
        run: |
          MODULES=$(git diff --name-only HEAD~1 HEAD | grep '^modules/' | cut -d'/' -f2 | sort | uniq | jq -R -s -c 'split("\n")[:-1]')
          if [[ -z "$MODULES" || "$MODULES" == "null" ]]; then MODULES="[]"; fi
          echo "modules=$MODULES" >> $GITHUB_OUTPUT

  publish:
    needs: determine-modules
    if: needs.determine-modules.outputs.modules != '[]'
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        module: ${{ fromJson(needs.determine-modules.outputs.modules) }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21**
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Verify Java version
        run: |
          echo "JAVA_HOME: $JAVA_HOME"
          java -version

      - name: Manually set JAVA_HOME**
        run: |
          export JAVA_HOME=$(dirname $(dirname $(readlink -f $(which java))))
          echo "export JAVA_HOME=$JAVA_HOME" >> $GITHUB_ENV
          echo "Updated JAVA_HOME: $JAVA_HOME"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.10'

      - name: Debug GitHub Token
        run: |
          echo "Base64 Encoded GITHUB_TOKEN:"
          echo $GITHUB_TOKEN | base64


      - name: Publish changed module
        run: ./gradlew :modules:${{ matrix.module }}:publish
        env:
          GITHUB_USERNAME: ${{ secrets.GH_USERNAME }}
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
