name: Publish toolkit to GitHub Packages

on:
  push:
    branches:
      - dev

jobs:
  determine-modules:
    runs-on: ubuntu-22.04
    outputs:
      modules: ${{ steps.changed-modules.outputs.modules }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.0

      - name: Determine changed modules
        id: changed-modules
        run: |
          MODULES=$(git diff --name-only HEAD^ HEAD | grep '^modules/' | cut -d'/' -f2 | sort | uniq | jq -R -s -c 'split("\n")[:-1]')
          
          # 변경된 모듈이 없으면 기본값 빈 배열 [] 제공
          if [[ -z "$MODULES" ]]; then
            MODULES="[]"
          fi

          echo "modules=$MODULES" >> $GITHUB_OUTPUT
          echo "Detected modules: $MODULES"

  publish:
    needs: determine-modules
    if: needs.determine-modules.outputs.modules != '[]'  # 변경된 모듈이 있을 때만 실행
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        module: ${{ fromJson(needs.determine-modules.outputs.modules) }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.5'

      - name: Publish changed module (${{ matrix.module }}) to GitHub Packages
        run: ./gradlew :modules:${{ matrix.module }}:publish
        env:
          GITHUB_USERNAME: ${{ secrets.GITHUB_USERNAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
